Frontend/HotelProject.WebUI/Controllers/AdminRoomController.cs
using HotelProject.WebUI.Dtos.RoomDto;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace HotelProject.WebUI.Controllers
{
    public class AdminRoomController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public AdminRoomController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync("http://localhost:5140/api/Room");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<List<ResultRoomDto>>(jsonData);
                return View(values);
            }

            return View();
        }

        [HttpGet]
        public IActionResult AddRoom()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> AddRoom(CreateRoomDto roomDto)
        {
            if (!ModelState.IsValid)
            {

                return View(roomDto);
            }

            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(roomDto);
            StringContent content = new StringContent(jsonData, Encoding.UTF8, "application/json");

            var responseMessage = await client.PostAsync("http://localhost:5140/api/Room", content);

            if (responseMessage.IsSuccessStatusCode)
            {

                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Oda eklenirken bir hata oluştu, lütfen tekrar deneyin.");
            return View(roomDto);
        }

        public async Task<IActionResult> DeleteRoom(int id)
        {
            
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.DeleteAsync($"http://localhost:5140/api/Room/{id}");
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        public async Task<IActionResult> UpdateRoom(int id)
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync($"http://localhost:5140/api/Room/{id}");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<UpdateRoomDto>(jsonData);
                return View(values);
            }
            return View();

        }

        [HttpPost]

        public async Task<IActionResult> UpdateRoom(UpdateRoomDto roomDto)
        {
            if (!ModelState.IsValid)
            {
                Console.WriteLine(0);
                return View(roomDto);
            }
            var client = _httpClientFactory.CreateClient();
            var jsonData = JsonConvert.SerializeObject(roomDto);
            StringContent stringContent = new StringContent(jsonData, Encoding.UTF8, "application/json");
            var responseMessage = await client.PutAsync($"http://localhost:5140/api/Room/", stringContent);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Servis eklenirken bir hata oluştu, lütfen tekrar deneyin.");
            return View(roomDto);

        }
    }
}

Frontend/HotelProject.WebUI/Views/AdminRoom/AddRoom.cshtml
@model CreateRoomDto

@{
    ViewData["Title"] = "AddRoom";
    Layout = "~/Views/AdminLayout/_AdminLayout.cshtml";
}

<form method="post">
    <label>Oda Numarası</label>
    <input type="text" asp-for="RoomNumber" class="form-control" />
    <br />
    <label>Oda Başlığı</label>
    <input type="text" asp-for="Title" class="form-control" />
    <br />
    <label>Fiyat</label>
    <input type="text" asp-for="Price" class="form-control" />
    <br />
    <label>Yatak Odası Sayısı</label>
    <input type="text" asp-for="BedCount" class="form-control" />
    <br />
    <label>Banyo Sayısı</label>
    <input type="text" asp-for="BathCount" class="form-control" />
    <br />
    <label>Oda Kapak Fotoğrafı</label>
    <input type="text" asp-for="RoomCoverImage" class="form-control" />
    <br />
    <label>Açıklama</label>
    <input type="text" asp-for="Description" class="form-control" />
    <br />
    <label>Wifi</label>
    <input type="text" asp-for="Wifi" class="form-control" />
    <br />
    <button class="btn btn-primary">Odayı Ekle</button>
</form>

Frontend/HotelProject.WebUI/Views/AdminRoom/Index.cshtml
@model List<ResultRoomDto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/AdminLayout/_AdminLayout.cshtml";
    int count = 0;
}

<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Oda Numarası</th>
        <th>Başlık</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        count++;
        <tr>
            <th>@count</th>
            <td>@item.RoomNumber</td>
            <td>@item.Title</td>
            <td>
                <a asp-controller="AdminRoom" asp-action="DeleteRoom" asp-route-id="@item.RoomId" class="btn mb-1 btn-rounded btn-outline-danger">Sil</a>
            </td>
            <td>
                <a asp-controller="AdminRoom" asp-action="UpdateRoom" asp-route-id="@item.RoomId" class="btn mb-1 btn-rounded btn-outline-success">Güncelle</a>
            </td>

        </tr>
    }
</table>
<a href="/AdminRoom/AddRoom/" class="btn mb-1 btn-rounded btn-outline-info">Yeni Oda Girişi</a>

Frontend/HotelProject.WebUI/Views/AdminRoom/UpdateRoom.cshtml
@model UpdateRoomDto

@{
    ViewData["Title"] = "UpdateRoom";
    Layout = "~/Views/AdminLayout/_AdminLayout.cshtml";
}

<form method="post">
    <input type="hidden" asp-for="RoomId" />
    <label>Oda Numarası</label>
    <input type="text" asp-for="RoomNumber" class="form-control" />
    <br />
    <label>Oda Başlığı</label>
    <input type="text" asp-for="Title" class="form-control" />
    <br />
    <label>Fiyat</label>
    <input type="text" asp-for="Price" class="form-control" />
    <br />
    <label>Yatak Odası Sayısı</label>
    <input type="text" asp-for="BedCount" class="form-control" />
    <br />
    <label>Banyo Sayısı</label>
    <input type="text" asp-for="BathCount" class="form-control" />
    <br />
    <label>Oda Kapak Fotoğrafı</label>
    <input type="text" asp-for="RoomCoverImage" class="form-control" />
    <br />
    <label>Açıklama</label>
    <input type="text" asp-for="Description" class="form-control" />
    <br />
    <label>Wifi</label>
    <input type="text" asp-for="Wifi" class="form-control" />
    <br />
    <button class="btn btn-primary">Odayı Güncelle</button>
</form>